//package oop3hometask1;
//public class ExcepyionDemo {
// static void compute (int a) throws MyException{
//        System.out.println("вызван метод compute"+a+")");
//        if (a>10)
//            throw new MyException (a);
//        System.out.println("нормальное завершение");
//    }
//
//}
